# Generated by Django 5.2.7 on 2025-11-05 10:29

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.profile_photo_upload_to, verbose_name='Photo de profil'),
        ),
    ]
